### ISSUE TITLE
It isn't clear how to obtain a "spec" object to pass in to "validate_spec" function.

### ISSUE THREAD

**Issue by jiss2891** [p1c2u/openapi-spec-validator#101]
After navigating through the code I found out that if you want to validate a `my_spec.yaml` you need to yaml load it using the ExtendedSafeLoader, I would love to see a clear API to do so:

This is a trimmed version of how my code looks like right now:

```python
from openapi_spec_validator import validate_spec
from openapi_spec_validator.exceptions import OpenAPIValidationError
from openapi_spec_validator.__main__ import read_from_filename


def validate_oas_file(spec_file):
    spec, _ = read_from_filename(spec_file)
    assert validate_spec(spec) is None
```

I found `read_from_filename` to be very handy and it would be nice to have a module to manage `readers`, as follows:

```python
from openapi_spec_validator.readers import read_from_filename
```

I didn't found something like this in the code, if there's such a thing, just forget this issue and please point me in the right direction.

Thanks.

**Comment by p1c2u** [comment]
Indeed worth to change make it clear.
