### ISSUE TITLE
Cannot import _legacy_validators

### ISSUE THREAD

**Issue by LukaSeequent** [p1c2u/openapi-spec-validator#112]
Hello

Just curious if the 0.2.10 build and 0.3.0 builds are broken for anyone else?

`from openapi_schema_validator.validators import OAS30Validator     File:/lib/python3.6/site-packages/openapi_schema_validator/validators.py, line 1`
`ImportError: cannot import name '_legacy_validators'`

We have had to roll back to 0.2.9 to make our builds work.

Thanks

Luka

**Comment by p1c2u** [comment]
Hi @LukaSeequent 
It looks like compatibility issue with jsonschema package. Which jsonschema package version you use?

**Comment by mvgadagi** [comment]
Hello,

We are getting the same error today and we are not using jsonschema package directly but it seems peer dependency of other packages and jsonschema version used is 2.0.6, could you please help me, how to resolve the issue?

Regards.
Mahesh

**Comment by p1c2u** [comment]
@mvgadagi 
that's what I thought. You just need to update jsonschema to version min 3.0

**Comment by p1c2u** [comment]
openapi-schema-validator 0.1.3 with jsonschema dependency fix was released hence closing the issue.
