### ISSUE TITLE
No longer windows compatible.

### ISSUE THREAD

**Issue by matthewdeanmartin** [p1c2u/openapi-spec-validator#117]
so if I run 
`openapi-spec-validator file.yml`

This code

    try:
        spec, spec_url = reader(args.filename)
    except Exception as exc:
        print(exc)
        sys.exit(1)

 throws 
`OSError: [Errno 22] Invalid argument: "'/C:/Users/matth/GitHub/openapi-spec-validator/file.yml'`

So what is happening is you are forcing a relative path to an absolute path and python doesn't know what to do with this sort of path (same problem for cmd.exe, and gitbash).

I tried commenting out the `filename = os.path.abspath(filename)` but it looks like downstream code is expecting URIs now. I'd recommend opening the file to read using the relative path your users provide and if later on you need a URI for whatever, then keep that separate from the string you use to open() a file.

0.2.9 used to work, so I'll pin to that.

48% of python developers use windows, so I'd guess half the people who use this run into the same problem, ref: https://www.zdnet.com/article/programming-languages-python-developers-reveal-what-they-use-it-for-and-their-top-tools/

Even if we really don't want to support anyone except for alpine linux or whatever, people use different shells on unix and I'd expect open() can't deal with everything any shell can throw at it.

**Comment by p1c2u** [comment]
Hi @matthewdeanmartin 

thanks for the report, I agree that's a big issue.

For me it looks like incorrect file path format is passed to `open` function.
