### ISSUE TITLE
setuptools are missing in requirements.txt

### ISSUE THREAD

**Issue by ZdenekM** [p1c2u/openapi-spec-validator#133]
`pkg_resources` (part of setuptools) are [imported](https://github.com/p1c2u/openapi-spec-validator/blob/27ee7cf747e7b45a4c41c2acef8fda7f96120c2a/openapi_spec_validator/schemas.py#L4), but `setuptools` are missing in requirements.txt.

**Comment by p1c2u** [comment]
It's fixed and released with version `0.3.3` hence closing
