### ISSUE TITLE
draft4_format_checker checkers removed

### ISSUE THREAD

**Issue by lucas03** [p1c2u/openapi-spec-validator#144]
Hey,
we are using custom checkers, as connexion suggests [here](https://connexion.readthedocs.io/en/latest/cookbook.html?highlight=%40draft4_format_checker#custom-type-format). For example, this is our currency checker:
```
@draft4_format_checker.checks("iso-4217")
def validate_currency(to_validate: Optional[str]) -> bool:
    """Validation for iso-4217 currency."""
    return to_validate is None or to_validate in locale.currencies
```
But since version `openapi-spec-validator-0.2.10` this no longer works. I noticed it's removed in [this commit](https://github.com/p1c2u/openapi-spec-validator/commit/fe3788875cd48928370a0731a1eb9ca9630a281e).  Is there a suggestion what should be used instead?

Error message:
```prance.ValidationError: ("Format checker for 'iso-4217' format not found", 'format', deque([]), None, [], 'iso-4217', 'EUR', {'type': 'string', 'default': 'EUR', 'format': 'iso-4217', 'nullable': False}, deque(['format']), None)```

**Comment by lucas03** [comment]
I've been looking into this for a while, since prance requires higher version of openapi-spec-validator now.

When creating connexion app, we are parsing openapi spec with `prance` lib:
```
    for specification_path in Path(package_path).rglob("openapi.yaml"):
        root_specification_filepath = path.join(specification_path)
        parser = ResolvingParser(root_specification_filepath, backend="openapi-spec-validator")
        base_path = parser.specification.get("servers", [{"url": "/"}])[0]["url"]
        connexion_app.openapi_schemas[base_path] = parser.specification

        connexion_app.add_api(
            parser.specification,
            validate_responses=True,
            strict_validation=True,
            resolver=RestyResolver(f"{package_name}.handlers"),
            validator_map=validator_map,
        )
```
but on this line, it is running validation on spec:
```
parser = ResolvingParser(root_specification_filepath, backend="openapi-spec-validator")
```
For some reason prance raises error here, as if the custom validator is not registered. We have it defined like this:
```
@jsonschema.Draft4Validator.FORMAT_CHECKER.checks("iso-4217")
def validate_currency(to_validate: str | None) -> bool:
    """Validation for iso-4217 currency."""
    return to_validate is None or to_validate in locale.currencies
```
when prance is running validation:
```
validate_spec(self.specification)
```
`SpecValidator` seems to yield errors. When checking SpecValidator instance, `self.schema_validator` seems to have all checkers loaded under `FORMAT_CHECKER` (12 checkers) (instance of `Draft4Validator`). 

`self.value_validator_class.FORMAT_CHECKER` however is an instance of `jsonschema.validators.create.<locals>.Validator` with 8 checkers and `self.value_validator_format_checker` is an instance of `OASFormatChecker` with 10 checkers.

I have a suspicion I should somehow make sure custom checkers are registered there, but I struggle debugging this.

**Comment by p1c2u** [comment]
@lucas03  Connexion example seems to be outdated. You should register new check with instance defined by `self.value_validator_format_checker` to make it work.

```python
@openapi_schema_validator.oas30_format_checker.checks("iso-4217")
def validate_currency(to_validate: Optional[str]) -> bool:
    """Validation for iso-4217 currency."""
    return to_validate is None or to_validate in locale.currencies
```

**Comment by lucas03** [comment]
Thank you for helpful reply 👍 

However tests on validation started failing, as some post body was validated before, but not after using:
```
@openapi_schema_validator.oas30_format_checker.checks("iso-4217")
def validate_currency(to_validate: Optional[str]) -> bool:
    """Validation for iso-4217 currency."""
    return to_validate is None or to_validate in locale.currencies
```
when I register checks for both validators, it works. Is this expected usage? 
```
@jsonschema.Draft4Validator.FORMAT_CHECKER.checks("iso-4217")
@openapi_schema_validator.oas30_format_checker.checks("iso-4217")
def validate_currency(to_validate: str | None) -> bool:
    """Validation for iso-4217 currency."""
    return to_validate is None or to_validate in locale.currencies
```

**Comment by p1c2u** [comment]
Make sure test uses the same validator and check is registered on setup stage (before test starts).

**Comment by lucas03** [comment]
I'd say import and init is fine, as it is registered. Isn't the problem in this code?
```
get_openapi_v30_schema_validator = partial(Draft4Validator, schema_v30)
openapi_v30_schema_validator = Proxy(get_openapi_v30_schema_validator)
get_openapi_v30_spec_validator = partial(
    SpecValidator,
    openapi_v30_schema_validator,
    OAS30Validator,
    oas30_format_checker,
    resolver_handlers=default_handlers,
)
```
`openapi_v30_schema_validator`  is `Draft4Validator` and `value_validator_class` initializes with`OAS30Validator`. But I am quite lost here, so have no idea.  
Worst case scenario I will use both decorators and I believe this can be closed.  
Thank you for help again and have a nice day.

**Comment by p1c2u** [comment]
> openapi_v30_schema_validator is Draft4Validator

Draft4Validator validates schema of spec and that schema is written in Draft4.
OAS30Validator validates default values in spec.

**Comment by lucas03** [comment]
What if custom value is in both. I assume for `Draft4Validator` it would be as `example: EUR` and for `OAS30Validator` it would be as `default: EUR`.

**Comment by p1c2u** [comment]
Afaik example(s) are not validated.

**Comment by lucas03** [comment]
Aaah, you are right, sorry for the confusion and wasting your time. I was writing from the top of my head.

The problem was if I used only `OAS30Validator` decorator, our tests would fail with a different error than before -> inside the code. Before, it would fail on schema validation. I now see that we override some validators ourselves, as connexion allowed us to pass [validator_map](https://connexion.readthedocs.io/en/latest/request.html#custom-validators) for body, parameter and response. And we use `jsonschema.Draft4Validator`. I assume if I replace those with `OAS30Validator`, that should fix it.

**Comment by lucas03** [comment]
hmm, should connexion by default implement `OAS30Validator` instead of `Draft4ResponseValidator` now?

**Comment by p1c2u** [comment]
hmm, I'm not up to date with connection right now and don't know `Draft4ResponseValidator`

I quick looked at `Draft4ResponseValidator ` and it has some extra validators included such as `x-nullable` and `x-writeOnly`.

**Comment by lucas03** [comment]
ok, thanks for your swift help. I'll use both decorators for now.
