### ISSUE TITLE
Yaml is converting date examples to datetime objects (not compatible with json serializer)

### ISSUE THREAD

**Issue by Tinky** [p1c2u/openapi-spec-validator#158]
Hi, I'm working with version 0.5.0a2

I have an api.yaml spec with parameter examples for a date field. I'm getting the following error:
$ openapi-spec-validator api.yaml
Object of type date is not JSON serializable

In handlers/file.py:
from yaml import load
from openapi_spec_validator.handlers.compat import SafeLoader

The error is triggered in handlers/file.py:FileObjectHandler.__call__ where it runs:
json.loads(json.dumps(load(f, self.loader)))

This is because yaml.load is identifying my date examples and creating datetime objects from them and then json is failing to convert them back to strings.

To get around it I hacked the compat file so Yaml ignored dates as described in: https://stackoverflow.com/questions/34667108/ignore-dates-and-times-while-parsing-yaml

**Comment by Tinky** [comment]
I have found another workaround for this.
Instead of:

          examples:
            shortDate:
              summary: Short Date Format YYYY-MM-DD
              value: 1985-04-12

I do:
          examples:
            shortDate:
              summary: Short Date Format YYYY-MM-DD
              value: '1985-04-12'

Adding the quotes around the value force a string and doesn't get converted to a date.

**Comment by TheErk** [comment]
Same here issue still exists in 0.5.1 is there any other ticket to track this issue
