### ISSUE TITLE
"Object of type datetime is not JSON serializable" error in version 0.5.1 but not in 0.4.0

### ISSUE THREAD

**Issue by firstStraw** [p1c2u/openapi-spec-validator#185]
When using the command `python3.9 -m openapi_spec_validator example.yml` where the `example.yml` file contains the following:

```
openapi: 3.0.0  
info:  
  title: Example OpenAPI  
  version: 0.0.1  
paths:  
  /mypath:  
    get:  
      parameters:  
        - name: myparam  
          in: query  
          schema:  
            format: date-time  
            type: string  
            example: 1997-07-16T19:20:30.45Z  
      responses:  
        '200':  
          description: Success  
```

The result is the error:
`Object of type datetime is not JSON serializable`

If the example timestamp value in the YAML is wrapped in quotes, then the error does not occur and the result is:
`OK`

This was observed with Python 3.9.16 and openapi-spec-validator 0.5.1.  When using openapi-spec-validator 0.4.0, the error does not occur.

**Comment by p1c2u** [comment]
Closing hence jsonschema-spec 0.1.3 solves the issue
