### ISSUE TITLE
$ref to external files raise RefResolutionError: unknown url type

### ISSUE THREAD

**Issue by viczem** [p1c2u/openapi-spec-validator#3]
The OpenAPI Specification allow to reference to external files: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#reference-object

But this validator is not fully implement the Reference Object of the specification. This shortcoming makes this library practically useless.

By the way, I did not see the full implementation of this object in other similar libraries.

**Comment by p1c2u** [comment]
@viczem 
Yes, it allows but you need to specify `spec_url` keyword argument to resolver know what is the relative path
