### ISSUE TITLE
Question: PyYAML vs pyaml dependency

### ISSUE THREAD

**Issue by pglass** [p1c2u/openapi-spec-validator#31]
There are two packages on PyPI whose package name differs by one character:

- [`PyYAML`](https://pypi.org/project/PyYAML/): This is the core YAML parser (what I would expect to be installed)
- [`pyaml`](https://pypi.org/project/pyaml/): This is "pretty yaml", which is built on top of PyYAML

`pyaml` ("pretty yaml") is the library installed in both [setup.py](https://github.com/p1c2u/openapi-spec-validator/blob/70f5731d80da88405df6945fcdd0cb4ee0612698/setup.py#L72) and in the [requirements.txt](https://github.com/p1c2u/openapi-spec-validator/blob/70f5731d80da88405df6945fcdd0cb4ee0612698/requirements.txt#L2)). Is `pyaml` actually needed/used or should that be switched to just install `PyYAML`?

**Comment by pglass** [comment]
I also suggest switching [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) because PyYAML has not received a release since Aug 29, 2016. Among other things, ruamel.yaml supports YAML 1.2, has received numerous bugfixes, and selects the fastest C-based loaders by default (when available)

**Comment by p1c2u** [comment]
@pglass you're right/ We don't need pyaml.

ruamel.yaml looks interesting to be a optional replacement but I'm curious about it's bad performance https://bitbucket.org/ruamel/yaml/issues/159/bad-performance-compared-to-pyyaml
