### ISSUE TITLE
Valid response definition shows validation error

### ISSUE THREAD

**Issue by rafaelcaricio** [p1c2u/openapi-spec-validator#33]
When using a valid OpenAPI spec (validated also by the swagger editor) an error is returned on the responses validation.

```
$ python -m openapi_spec_validator ~/development/draft/api.yaml
{'description': 'Changed with success.', 'content': {'application/json': {'schema': {'$ref': '#/components/responses/GenericSuccess', 'x-scope': ['file:///development/draft/api.yaml']}}}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['post']['properties']['responses']['patternProperties']['^([0-9X]{3})$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/reference'}]}

On instance['paths']['/pets/{id}/comments']['post']['responses']['200']:
    {'content': {'application/json': {'schema': {'$ref': '#/components/responses/GenericSuccess',
                                                 'x-scope': ['file:///development/draft/api.yaml']}}},
     'description': 'Changed with success.'}
```

The spec looks like:
```yaml
...
    put:
      summary: Comments.
      operationId: api.change
      requestBody:
        description: Something.
        required: true
        content:
          applicaton/json:
            schema:
              $ref: '#/components/schemas/CChange'
      responses:
        "200":
          description: Changed with success.
          content:
            application/json:
              schema:
                $ref: '#/components/responses/GenericSuccess'
...
```

This should not throw an exception. Because the API spec is valid as of https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responseObject Unless I'm missing something here.

**Comment by rafaelcaricio** [comment]
This error seems to be because of the automatically added by default "x-scope" field to the reference level. References cannot have "x-" extension properties unless you change the  [JSONSchema spec for OpenAPI 3.0.0](https://github.com/p1c2u/openapi-spec-validator/blob/master/openapi_spec_validator/resources/schemas/v3.0.0/schema.json#L715-L727).

**Comment by rafaelcaricio** [comment]
Ok, after hours of investigation I figured I am wrong. Your code is correct. ;)

**Comment by HRogge** [comment]
I am running into the same issue...
@rafaelcaricio Could you maybe state what you found out that made you think the code is correct?

**Comment by rafaelcaricio** [comment]
@HRogge My problem was because of the referenced part of the API was wrong. If you see in my example above I reference `$ref: #/components/responses/GenericSuccess` which refines an complete [response object](https://swagger.io/specification/#responseObject) not a [schema object](https://swagger.io/specification/#schemaObject).

In my case I fixed by referencing the correct part of the spec, something like `$ref: '#/components/schemas/GenericMessage'`.

I hope that helps you!

**Comment by HRogge** [comment]
@rafaelcaricio  Thank you for the quick response... my problem is unfortunately different.
