### ISSUE TITLE
Can't install through pip

### ISSUE THREAD

**Issue by jkklapp** [p1c2u/openapi-spec-validator#5]
When I try to install the package I get the following output.

```
Collecting openapi-spec-validator
  Could not find a version that satisfies the requirement openapi-spec-validator (from versions: )
No matching distribution found for openapi-spec-validator
```

**Comment by p1c2u** [comment]
@jkklapp  Are you using python3?

**Comment by mrichar1** [comment]
Might not be this, but I notice that pypi only hosts wheels for openapi-spec-validator - which easy_install and older versions of pip don't support.

**Comment by p1c2u** [comment]
@mrichar1 that can be the case too. I've uploaded source tar.gz version so it should work with old pip/easy_install

**Comment by jkklapp** [comment]
@p1c2u I'm using python2

**Comment by p1c2u** [comment]
@jkklapp ok so it's a python3 implementation

**Comment by p1c2u** [comment]
@dtkav added python 2.7 support. We can close the issue.
