### ISSUE TITLE
Q: how to validate spec files?

### ISSUE THREAD

**Issue by BenjamenMeyer** [p1c2u/openapi-spec-validator#6]
I see your examples in the README.md, but I'm writing a spec file from scratch in YAML and want to valid that what I'm writing is correct. All your examples provide a `spec_dict` value but no information on what it is. As it stands, the examples look more like an input validator for HTTP calls by a client versus  validating the spec data itself. Could you please clarify:
- how to validate the spec file being written
- what `spec_dict` is

Thanks!

**Comment by p1c2u** [comment]
@BenjamenMeyer You're right. I didn't mention that `spec_dict` needs to be `dict` with OpenAPI spec. If you want to validate file you just need to parse file first. To do that you can use `safe_load` from `yaml` package.

**Comment by BenjamenMeyer** [comment]
@p1c2u how does that work with the reference objects? I'm working on a relatively large API and looking to use multiple files to keep the spec as DRY as possible.

**Comment by p1c2u** [comment]
@BenjamenMeyer you need to pass `spec_url`. Look at the usage example in README.

**Comment by BenjamenMeyer** [comment]
gotcha..yeah; I had tried out the `validate_spec_url` but had some issue...got it working now. THanks!
