### ISSUE TITLE
Timeouts reading large description files

### ISSUE THREAD

**Issue by alansill** [p1c2u/openapi-spec-validator#64]
Reading a large OpenAPI YAML file that refers to many subcomponent $ref references on the web, I am encountering "timed out" messages partway through pulling in the description.

1) Is this timeout controllable?

2) Can OpenAPI input be provided through a URL rather than just by a local starting YAML file?

**Comment by p1c2u** [comment]
@alansill 
1. Not for now but it is possible to do so
https://github.com/p1c2u/openapi-spec-validator/blob/master/openapi_spec_validator/handlers.py#L25
2. Yes, you can use `validate_spec_url` (check README file)

**Comment by alansill** [comment]
Thanks. Worked around these issues by creating a combined single description file using swagger-combine.
