### ISSUE TITLE
update the dependency

### ISSUE THREAD

**Issue by pingf** [p1c2u/openapi-spec-validator#66]
please update jsonschema to v3 in requirements, or it will fail with dependency check when I use frameworks such as connexion

**Comment by dtkav** [comment]
@pingf both connexion and openapi-spec-validator require jsonschema < 3.

**Comment by pingf** [comment]
sorry, it seems it's the problem of poetry, here is the related issue sdispater/poetry#532

**Comment by p1c2u** [comment]
Version `0.2.7` should support both jsonschema 2 and 3.
